### ISSUE TITLE
Should GCP Cache strategy do redirect?

### ISSUE THREAD

**Issue by swangee** [transifex/transifex-delivery#83]
Hello,
I haven't found the answer in the documentation for the following issue:
I use the GCP bucket as the cache backend and got 302 redirects trying to open and file.
The location of the redirect is the url of the file on the GCP. Is it valid behavior?

I thought that files would be served right from the hosted CDS. Is using Redis cache the only way to achieve that behavior?

**Comment by nbasili** [comment]
Hello, yes the redirect is the valid behaviour. The whole point of using the GCP bucket it to be able to leverage Google's CDN for edge content delivery.

The Native SDKs are making a request to the CDS endpoint, and it returns a super-fast 302 response to Google CDNs, so that the user can download the content, based on their location.

To serve directly from CDS service, you can either skip setting `TX__CACHE__GCS__LOCATION` environment variable or set it to `TX__CACHE__GCS__LOCATION="cache://"`, which is the default. In that case, the CDS will read the files from your GCP bucket and stream it back. But this is slower.

**Comment by swangee** [comment]
Thanks very much for the response.

It would be grate to add this information to the docs.

Have a great day!

**Comment by swangee** [comment]
Thanks very much for the response.

It would be grate to add this information to the docs.

Have a great day!
